# https://lukasgeiter.github.io/mkdocs-awesome-nav/
nav:
  - index.md
  - Internals:
    - Overview: overview.md
    - configuration-properties.md
    - Logical Operators: logical-operators
    - "*"
  - Python:
    - python.md
    - spark_connect_pipeline.md
  - SQL:
    - sql.md
  - Demo: demo
