# https://lukasgeiter.github.io/mkdocs-awesome-nav/
nav:
  - index.md
  - Auto CDC: auto-cdc
  - Internals:
    - Overview: overview.md
    - configuration-properties.md
    - Logical Operators: logical-operators
    - "*"
  - CLI: cli
  - PySpark: pyspark
  - SQL:
    - sql.md
  - Spark Connect: spark-connect
  - Demos: demo
